# Generated by Django 4.1 on 2022-09-07 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='PhoneNumber',
            new_name='contact',
        ),
        migrations.CreateModel(
            name='Leave_Application',
            fields=[
                ('application_id', models.IntegerField(default=' ', primary_key=True, serialize=False)),
                ('To_date', models.DateField()),
                ('From_date', models.DateField(blank=True, null=True)),
                ('Reason', models.CharField(max_length=200, null=True)),
                ('leave_status', models.BooleanField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.IntegerField(default=' ', primary_key=True, serialize=False)),
                ('leaves_name', models.CharField(max_length=100, null=True)),
                ('total_leave', models.CharField(max_length=100, null=True)),
                ('consume_leave', models.CharField(max_length=100, null=True)),
                ('balance_leave', models.CharField(max_length=100, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(default=' ', primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=200, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
