# Generated by Django 4.1 on 2022-09-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0002_rename_phonenumber_userdetail_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
                ('contact', models.CharField(default=0, max_length=6)),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
