# Generated by Django 4.1 on 2022-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(default='', max_length=6),
        ),
    ]
