# Generated by Django 4.1 on 2022-09-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0004_alter_registration_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
