# Generated by Django 3.1.7 on 2022-09-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0006_auto_20220909_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
                ('contact', models.CharField(default='', max_length=6)),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='contact',
            new_name='contact_id',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='User',
        ),
    ]
