# Generated by Django 3.1.7 on 2022-09-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0007_auto_20220909_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
