# Generated by Django 3.1.7 on 2022-09-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0008_auto_20220909_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_type',
            field=models.CharField(default='', max_length=500),
        ),
    ]
